### ISSUE TITLE
Error after upgrading to macOS High Sierra

### ISSUE THREAD

**Issue by agarrharr** [lucasefe/ta#2]
Thanks for making such a great tool! I just thought I would let you know about a problem when I upgraded to macOS High Sierra.

When I run `ta`, I get this error:

```sh
fatal error: unexpected signal during runtime execution
fatal error: systemstack called from unexpected goroutine
fatal error: systemstack called from unexpected goroutine
fatal error: systemstack called from unexpected goroutine
fatal error: systemstack called from unexpected goroutine
fatal error: systemstack called from unexpected goroutine
```

There's actually a lot more of the same error repeated.

**Comment by bachya** [comment]
Confirmed, same here.

**Comment by lucasefe** [comment]
Damn, just saw this. I'll get to it.

**Comment by lucasefe** [comment]
Upgrading to 0.3.2 solves the issue. Sorry for the wasted time and lack of response. I'll make sure next time I get notifications from this repo.
